### PR TITLE
update myservices of modify, scale api for end user.

### PR DESCRIPTION
**Pull request by Alice1319**
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1936

Scale for end user:
image

image

Modify for end user:
image

image

Migrate for end user:
image

### CODE REVIEW

**Review by swaroopar — CHANGES_REQUESTED** [review]
please fix error reported by CI job.

**Comment by Alice1319** [comment]
> please fix error reported by CI job.

fixed.

**Comment by dengyali0125** [comment]
lgtm

**Review by swaroopar — APPROVED** [review]
LGTM

**Pull request merged**
