### PR TITLE
show result message when deploy or destroy failed.

### PR DESCRIPTION
**Pull request by baixinsui**
chrome_9oRdxKF6Jq

### CODE REVIEW

**Comment by iskey** [comment]
would it be a bit of crowdy to show it here?

**Comment by baixinsui** [comment]
> would it be a bit of crowdy to show it here?

Change the size of the prompt area as the service information displayed after the deployment is successful？

**Review by iskey — APPROVED** [review]
looks good.

**Review by iskey — APPROVED** [review]
looks good.

**Pull request merged**
