### PR TITLE
introduce CSS modules for all styles

### PR DESCRIPTION
**Pull request by swaroopar**
fixes https://github.com/eclipse-xpanse/xpanse/issues/1628

### CODE REVIEW

**Comment by swaroopar** [comment]
@iskey no functional changes. Only migration of CSS to CSS-Modules

**Comment by Alice1319** [comment]
LGTM

**Review by iskey — APPROVED** [review]
LGTM

**Comment by iskey** [comment]
> @iskey no functional changes. Only migration of CSS to CSS-Modules

ok, @swaroopar , It looks good.

**Pull request merged**
