### PR TITLE
refactor form value store

### PR DESCRIPTION
**Pull request by swaroopar**
related to https://github.com/eclipse-xpanse/xpanse/issues/806

fix findings with current deploy variables store. 
current issues
1. Only last entered form field is stored. 
2. sometimes the last character is not stored. 
3. Default values are stored. We must store only user entered values.

### CODE REVIEW

**Comment by swaroopar** [comment]
@Alice1319 can you please check these changes and see if it works? currently the behavior is very random so I changed it to very simple way of handling deploy variables. If this works fine, we must do the same for migrate also.

**Comment by Alice1319** [comment]
> @Alice1319 can you please check these changes and see if it works? currently the behavior is very random so I changed it to very simple way of handling deploy variables. If this works fine, we must do the same for migrate also.

sure

**Comment by Alice1319** [comment]
it works fine.

**Comment by Alice1319** [comment]
LGTM

**Review by iskey — APPROVED** [review]
LGTM

**Pull request merged**
