### PR TITLE
use version and csp filter flavor.

### PR DESCRIPTION
**Pull request by Alice1319**
fixes eclipse-xpanse/xpanse#691

image

image

Migrate:
image

image

### CODE REVIEW

**Review by swaroopar — APPROVED** [review]
LGTM

**Review by swaroopar — CHANGES_REQUESTED** [review]
@Alice1319 as mentioned in the issue, we have the same problem in the migrate service too.  Even that must be fixed.

**Comment by Alice1319** [comment]
> @Alice1319 as mentioned in the issue, we have the same problem in the migrate service too. Even that must be fixed.

sure

**Review by swaroopar — APPROVED** [review]
LGTM

**Pull request merged**
