### PR TITLE
handle adding multiple credentials

### PR DESCRIPTION
**Pull request by WangLiNaruto**
Fixed eclipse-xpanse/xpanse#661

### CODE REVIEW

**Review by swaroopar — CHANGES_REQUESTED** [review]
@WangLiNaruto did you also check the last point in the user story?

**Comment by WangLiNaruto** [comment]
@swaroopar Yes, I left the "Name" field always on, left it empty and disabled. It is enabled when "Type" is selected.

**Comment by WangLiNaruto** [comment]
> @WangLiNaruto did you also check the last point in the user story?

Yes, I left the "Name" field always on, left it empty and disabled. It is enabled when "Type" is selected.

**Comment by Alice1319** [comment]
looks good

**Review by swaroopar — APPROVED** [review]
LGTM

**Pull request merged**
